name: donation_app
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  fluttertoast: ^8.2.8
  form_field_validator: ^1.1.0
  lottie: ^3.1.2
  shimmer_effect: ^1.0.4
  flutter_spinkit: ^5.2.1
  timelines: ^0.1.0
  fl_chart: ^0.69.0
  introduction_screen: ^3.1.14
  pin_code_fields: ^8.0.1
  fancy_popups_new: ^0.0.6
  dio: ^5.7.0
  flutter_stripe: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    -  assets/images/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
